/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Orbital Intelligence Design System Tokens
        'surface': '#0c1324',
        'surface-dim': '#0c1324',
        'surface-bright': '#33394c',
        'surface-container-lowest': '#070d1f',
        'surface-container-low': '#151b2d',
        'surface-container': '#191f31',
        'surface-container-high': '#23293c',
        'surface-container-highest': '#2e3447',
        'on-surface': '#dce1fb',
        'on-surface-variant': '#bbc9cd',
        'inverse-surface': '#dce1fb',
        'inverse-on-surface': '#2a3043',
        'outline': '#859397',
        'outline-variant': '#3c494c',
        'surface-tint': '#2fd9f4',
        'primary': '#8aebff',
        'on-primary': '#00363e',
        'primary-container': '#22d3ee',
        'on-primary-container': '#005763',
        'inverse-primary': '#006877',
        'secondary': '#7bd1fa',
        'on-secondary': '#003547',
        'secondary-container': '#00799e',
        'on-secondary-container': '#e9f6ff',
        'tertiary': '#68f5b8',
        'on-tertiary': '#003824',
        'tertiary-container': '#46d89d',
        'on-tertiary-container': '#005a3d',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#a2eeff',
        'primary-fixed-dim': '#2fd9f4',
        'on-primary-fixed': '#001f25',
        'on-primary-fixed-variant': '#004e5a',
        'secondary-fixed': '#c0e8ff',
        'secondary-fixed-dim': '#7bd1fa',
        'on-secondary-fixed': '#001e2b',
        'on-secondary-fixed-variant': '#004d66',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'background': '#0c1324',
        'on-background': '#dce1fb',
        'surface-variant': '#2e3447',

        // Midnight OLED Palette
        'midnight': {
          'base': '#000000',
          'surface': '#05070f',
          'panel': '#080d1a',
          'border': '#111827',
        }
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'grid-overlay-size': '64px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Geist', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'headline-md': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'mono-label': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'mono-data': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'mono-label': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'mono-data': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      animation: {
        'pulse-glow': 'pulseGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        pulseGlow: {
          '0%, 100%': { opacity: '1', filter: 'drop-shadow(0 0 8px rgba(34, 211, 238, 0.6))' },
          '50%': { opacity: '0.5', filter: 'drop-shadow(0 0 2px rgba(34, 211, 238, 0.2))' },
        },
      },
    },
  },
  plugins: [],
};
